### ISSUE TITLE
Allow the mouse wheel to zoom in and out of the map

### ISSUE THREAD

**Issue by almccon** [americanpanorama/panorama-forcedmigration#16]
The panorama visualzations are somewhere between a full page map (where we usually have scroll-to-zoom enabled) and a map embedded in a webpage (where we always have scroll-to-zoom disabled) I am ambivalent. 

I wonder what @ericrodenbeck thinks.

**Comment by ericrodenbeck** [comment]
Let's go for scrolling. 

---

Eric Rodenbeck, CEO
Stamen Design LLC
http://stamen.com/
415.558.1610

"A good sketch is better than a long speech."—Napoléon Bonaparte
