### ISSUE TITLE
Site load blocked due to mixed content

### ISSUE THREAD

**Issue by almccon** [americanpanorama/panorama-forcedmigration#26]
Reported in this thread on twitter: https://twitter.com/Castillonis/status/898044050065965058

Specifically: "load of cartodb.core.js blocked and xhr sql blocked."

Is this a dupe of https://github.com/americanpanorama/panorama-foreignborn/issues/18, that we only fixed in Foreign Born, but not in Forced Migration? Or is it a new error surfacing?

**Comment by almccon** [comment]
From the tweet:
![dhaa1t7uiaa1yyl](https://user-images.githubusercontent.com/1212178/29422172-3ec0b972-832c-11e7-87c4-1a5829e90249.jpg)
![dhz-jp-vyaqkzky](https://user-images.githubusercontent.com/1212178/29422173-3ec840d4-832c-11e7-8389-46eea4e9bdd8.jpg)

**Comment by rnelson2** [comment]
now more-or-less working over https. Stamen's openterrain tiles aren't servable via ssl.
