### ISSUE TITLE
Intro modal: Consider adding a tutorial with a “how to” for the different sections.

### ISSUE THREAD

**Issue by almccon** [americanpanorama/panorama-forcedmigration#8]
Written response from Student #2: “Create a little tutorial that would show how to navigate through the website, how to use the tools.”

**Comment by emilyhobson** [comment]
@nicolettehayes Can you devise the design for this treatment? Framework should be usable for each of the different sites though customized for their specific information.

**Comment by emilyhobson** [comment]
Copy changes from Rob

http://studio.stamen.com/richmond/blog/2016/06/16/introduction-designs-2/#comments

**Comment by sconnelley** [comment]
New copy and steps 4 & 2 swapped
![image](https://cloud.githubusercontent.com/assets/565486/17790996/e047f61e-654d-11e6-93b1-5249d6c72807.png)
